payapp/urls.py
from django.urls import path, include
from payapp.views.accountant_and_position import (index,
                                                  PositionDetailView,
                                                  accountant_creation,
                                                  accountant_update,
                                                  login_user,
                                                  accountant_details,
                                                  change_password, 
                                                  PositionCreateView,
                                                  PositionListView,
                                                  PositionUpdateView,
                                                  logout_view
                                                  )

from payapp.views.employee import (employee_creation, 
                                   view_employee, 
                                   employee_update,
                                   employee_details,
                                #    payment_create,
                                    PayementCreateView,
                                   show_employee_balance,
                                   PaymentListView,
                                   view_transaction_details,
                                   UserListView,
                                   show_beruju,
                                   )
app_name="payapp"

urlpatterns = [
    # Home Page and others
    path('', index, name='index'),
    # Accountant Related
    path('accountant/create/',accountant_creation, name='accoutant_create'),
    path('accountant/update/self/',accountant_update, name='accountant_update'),
    path('accountant/details/', accountant_details, name='accountant_details'),
    # Position Related
    path('position/create/',PositionCreateView.as_view(), name='position_create'),
    path('position/',PositionListView.as_view(),name="position_list"),
    path('position/detail/<int:id>/', PositionDetailView.as_view(),  name="position_detail"),
    path('position/update/<int:id>/', PositionUpdateView.as_view(),name='position_update'),
    # Employee
    path('employee/create/', employee_creation, name='employee_create'),
    path('employee/',view_employee, name='employee_list'),
    path('employee/details/',employee_details, name='employee_details'),
    path('employee/update/self/',employee_update, name='employee_update'),
    # Authentication Related
    path('change-password/',change_password,name='change_password'),
    path('login/',login_user, name='login'),
    path('logout/',logout_view,name='logout'),
    # Payments related
    # path('payments/create/',payment_create,name='payment_create'),
    path("payments/create/",PayementCreateView.as_view(),name='payment_create'),
    path('payments/',PaymentListView.as_view(),name='payment_list'),
    # Employee balance
    path('balance/<int:id>/',show_employee_balance, name='balance'),
    #Salary Transaction
    path('transaction/<int:id>/',view_transaction_details,name='transaction'),
    # User list
    path('users/',UserListView.as_view(),name='users_list'),
    # Beruju
    path('beruju/<int:id>/',show_beruju,name='beruju_show')
]

paystation/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include('payapp.urls')),
]

payapp/views/accountant_and_position.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from ..forms import UserStaffForm, PositionForm, UserEditForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate, logout
from ..models import Accountant, Position
from django.views.generic import CreateView, ListView, DetailView, DeleteView,UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse,reverse_lazy
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash



# Create your views here.

def index(request):
    return render(request, 'payapp/index.html');

def accountant_creation(request): 
    if request.method == "POST":
        user_form = UserStaffForm(request.POST)
        if user_form.is_valid():
            print(user_form.cleaned_data)
            accountant = user_form.save()
            Accountant.objects.create(accountant = accountant, is_admin=user_form.cleaned_data['admin_status'])
            print("accountant created sucessfully.")
            return redirect('payapp:login')
    elif request.method =="GET":
        user_form = UserStaffForm()
    context = {'user':user_form}
    return render(request, 'payapp/signup.html',context)
        
def login_user(request):
    if request.method == "POST":
        form= AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            print('valid form')
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                print("logged in")
                return redirect('payapp:index')
    elif request.method == "GET":
            form = AuthenticationForm()
    context = {'user':form}
    return render(request, 'payapp/login.html',context)


@method_decorator(login_required(login_url=reverse_lazy('payapp:login')),name="dispatch")
class PositionCreateView(CreateView,LoginRequiredMixin):
    model = Position
    form_class = PositionForm
    success_url = reverse_lazy('payapp:position_list')
    template_name = 'payapp/position_create.html'
    
@method_decorator(login_required(login_url=reverse_lazy('payapp:login')),name="dispatch")
class PositionListView(ListView):
    model = Position
    context_object_name = 'positions'
    # template_name = 'payapp/list_position.html'

@method_decorator(login_required(login_url=reverse_lazy('payapp:login')),name="dispatch")
class PositionDetailView(LoginRequiredMixin,DetailView):
    model = Position
    pk_url_kwarg= 'id'
    context_object_name='object'
    # template_name = "payapp/detail_position.html"

@method_decorator(login_required(login_url=reverse_lazy('payapp:login')),name="dispatch")
class PositionUpdateView(LoginRequiredMixin,UpdateView):
    model = Position
    form_class = PositionForm
    pk_url_kwarg= 'id'
    success_url = reverse_lazy('payapp:position_list')

    
    
@login_required
def logout_view(request):
    logout(request)
    return redirect('payapp:index')


def change_password(request):
    if(request.method == "POST"):
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect('payapp:index')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    context = {'form':form}
    return render(request, 'payapp/change_password.html', context)


def accountant_update(request):
    context = {}
    user = request.user
    if request.method == "GET":
        form = UserEditForm(instance=user)
        context['form'] = form
    elif request.method == "POST":
        form = UserEditForm(request.POST, instance=user)
        # print(form)
        print(form.is_valid())
        if form.is_valid():
            print(form.cleaned_data)
            form.save()
            return redirect('payapp:index')
        context['form'] = form
    file_path = 'payapp/accountant_update.html'
    # file_path = 'payapp/update_accountant.html'
    return render(request,file_path,context)

def accountant_details(request):
    return render(request,'payapp/accountant_details.html')

payapp/views/employee.py
from django.shortcuts import render, redirect
from django.urls import reverse,reverse_lazy
from django.http import HttpResponse, JsonResponse,HttpResponseRedirect
from ..forms import PaymentForm, UserEmployeeForm, EmployeeForm, UserEditForm
import stripe
from ..models import Employee, Payment
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView
from django.contrib.auth.models import User
import datetime
from django.views.generic import CreateView
from django.utils.decorators import method_decorator


stripe.api_key = "sk_test_51LFDP4IhxTYC5XjyJ4mJo4Zc48CSnR89ZPCb4RRqdBALg1cQQajUZWFV1m3GvxJlLQOvNQo3AYGOXyxO8F7UpPaY00Gdo1cwvA"
tax_fund_account = "acct_1Lz101IdZsEKyeut"

@login_required(login_url=reverse_lazy('payapp:login'))
def employee_creation(request): 
    if request.method == "POST":
        user_form = UserEmployeeForm(request.POST)
        employee_form = EmployeeForm(request.POST)
        if user_form.is_valid():
            user = user_form.save()
            user_employee=employee_form.save(commit=False)
            user_employee.employee = user
            email = user.email
            print(email) 
            val = stripe.Account.create(type="standard", email=email)
            print(val['id'])
            user_employee.strip_account_id = val['id']
            user_employee.save()
            print(user_employee)
            print(user)
            return redirect('payapp:position_list')
    elif request.method =="GET":
        user_form = UserEmployeeForm()
        employee_form = EmployeeForm()
    context = {'user':user_form,'employee':employee_form}
    return render(request, 'payapp/employee_register.html',context)


@login_required(login_url=reverse_lazy('payapp:login'))
def view_employee(request):
    context = {}
    employees = Employee.objects.all()
    context['employees']= employees
    return render(request,'payapp/employee_list.html',context)


def employee_update(request):
    context = {}
    user = request.user
    if request.method == "GET":
        form = UserEditForm(instance=user)
        employee = user.employee
        user_form = EmployeeForm(instance = employee)
        context['form'] = form
        context['employee_form'] = user_form
    elif request.method == "POST":
        form = UserEditForm(request.POST, instance=user)
        employee = user.employee        
        user_form = EmployeeForm(request.POST,instance =  employee)
        if form.is_valid() and user_form.is_valid():
            # print(form.cleaned_data)
            form.save()
            user_form.save()
            return redirect('payapp:index')
        context['form'] = form
        context['employee_form'] = user_form
    return render(request,'payapp/employee_update.html',context)

def employee_details(request):
    return render(request,'payapp/employee_details.html')

class PayementCreateView(CreateView):
    model = Payment
    form_class = PaymentForm
    template_name = 'payapp/payment_create.html'
    # template_name = 'payapp/create_payment.html'
    success_url = reverse_lazy('payapp:index')

    def get_form(self, form_class=None):
        """Returns an instance of the form to be used in this view."""
        if form_class is None:
            form_class = self.get_form_class()
        return form_class(accountant = self.request.user.accountant,**self.get_form_kwargs())
    
    def post(self, request, *args, **kwargs):
        """
        Handles POST requests: instantiate a form instance with the passed
        POST variables and then check if it's valid.
        """
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form.cleaned_data)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        """If the form is valid, save the associated model."""
        accountant = self.request.user.accountant
        (tax_amount,
        pf_amount,
        paid_salary,
        employee,
        pf_percent,
        payment_month,
        user_salary) = self.deduct_amount(form)
        today = datetime.date.today()            
        transfer_dict = stripe.Transfer.create(amount=int(paid_salary),
                             currency="usd",
                             destination=employee.strip_account_id,
                                )
        tax_dict = stripe.Transfer.create(amount=int(tax_amount), currency="usd", destination=tax_fund_account)        
        pay = self.model.objects.create(
            payment_pf_percent = pf_percent,
            pf_amount = pf_amount,
            user_salary = user_salary,
            payment_month = payment_month,
            paid_salary = paid_salary,
            payment_date = today,
            tax_amount = tax_amount,
            stripe_transaction_id = transfer_dict.id,
            accountant = accountant,
            employee = employee 
            )
        print("transfer sucess.")
        return HttpResponseRedirect(reverse_lazy('payapp:index'))
        
    def deduct_amount(self,form):
        '''Custom Function for deducting tax, provident fund and misc tax.'''
        employee_obj = form['employee']
        total_salary = form['total_salary']
        payment_month = form['payment_month']
        pf_percent = employee_obj.pf_percent
        pf_amount = ((pf_percent)/100)*(total_salary)
        deducted_salary = total_salary - pf_amount
        tax_amount = (1/100)*(deducted_salary)
        paid_salary = deducted_salary - tax_amount
        user_salary = employee_obj.position.base_salary
        return tax_amount,pf_amount,paid_salary,employee_obj,pf_percent,payment_month,user_salary  



class PaymentListView(ListView):
    model = Payment
    context_object_name = 'payments'
    # template_name = "payapp/list_paym,.html"

@method_decorator(login_required(login_url=reverse_lazy('payapp:login')),name="dispatch")    
class UserListView(ListView):
    template_name = "payapp/user_list.html"
    # template_name = "payapp/list_user.html"
    model = User
    context_object_name = 'users'
    
    
def show_employee_balance(request,id):
    payments = Payment.objects.filter(employee = id)
    context = {}
    total_salary = 0.0
    total_provident_fund = 0.0
    total_tax = 0.0
    for payment in payments:
        total_salary += payment.paid_salary
        total_provident_fund += payment.pf_amount
        total_tax += payment.tax_amount
    context['total_salary'] = total_salary
    context['total_provident_fund'] = total_provident_fund
    context['total_tax'] = total_tax
    return render(request, 'payapp/balance_view.html',context)


def view_transaction_details(request,id):
    context = {}
    transaction = Payment.objects.filter(employee = id)
    context['transactions'] = transaction
    return render(request,'payapp/salary_list.html',context)



def show_beruju(request,id):
    if request.method == "GET":
        employee = Employee.objects.get(id=id)
        print(employee)
        transactions = Payment.objects.filter(employee =employee)
        beruju = 0
        for pay in transactions:
            # print(pay.user_salary, pay.paid_salary, pay.payment_month)
            # Change to deducted_salary
            deducted_salary = pay.paid_salary + pay.tax_amount
            # print(deducted_salary)
            # change to total_salary
            total_salary = deducted_salary + pay.pf_amount
            # print(total_salary)
            if(pay.payment_month>1):
                # print(pay.user_salary, pay.payment_month)
                to_be_salary = pay.user_salary*pay.payment_month
            else:
                to_be_salary = pay.user_salary
            salary_gap = total_salary - to_be_salary
            beruju +=salary_gap
        print(beruju)
        context = {}
        if(beruju > 0 ):
            context['beruju'] = "yes"
            context['beruju_amount'] = beruju
        else:
            context['beruju'] = 'No Beruju'
        return JsonResponse(context, status = 200)
    return redirect('payapp:employee_list')

payapp/templates/payapp/accountant_details.html
{% load static %}
<!DOCTYPE html> 
<html lang="en">
  <title>Hamro Khata | Welcome</title>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS Stylesheet -->
    <link rel="stylesheet" href="{% static 'css/detail_view.css'%}">
    <!-- Fontawesome -->
    <script src="https://kit.fontawesome.com/ae4127b743.js" crossorigin="anonymous"></script>
</head>
<body>
    <div class="header">
        <nav class="navbar">
          <div class="content">
            <div class="logo">
              <a href="{% url 'payapp:index'%}"><i class="fa-solid fa-pen-to-square"></i> Hamro Khata</a>
            </div>
            <ul class="menu-list">
              <div class="icon cancel-btn">
                <i class="fas fa-times"></i>
              </div>
              {% if user.is_authenticated %}
              {%if not user.is_staff%}
                <!-- Employee Status -->
                <li><a href="{% url 'payapp:balance' user.employee.id%}">View Balance</a></li>
                <li><a href="{% url 'payapp:employee_details'%}">Your Details</a></li>        
              {% else %}
                {% if not user.is_superuser %}
                  {% if user.accountant.is_admin %}
                  <!-- Admin Accountant Status -->
                  <li><a href="{% url 'payapp:payment_list' %}">Transactions</a></li>
                  <li><a href="https://dashboard.stripe.com/acct_1Lz101IdZsEKyeut/test/balance">Tax Fund</a></li>
                  {% endif %}
                  <!--Accountant Status -->
                  <li><a href="{% url 'payapp:payment_create'%}">Pay Salary</a></li>
                  <li><a href="{% url 'payapp:accountant_details'%}">Your Details</a></li>
                  <li><a href="{% url 'payapp:employee_list' %}">Employee</a></li>
                {% elif user.is_superuser %}
                <!-- Super User Status -->
                <li><a href="{% url 'admin:index' %}">Admin Panel</a></li>
                <li><a href="{% url 'payapp:users_list'%}">System Users</a></li>
                {% endif %}
              {% endif %}
              <li><a href="{% url 'payapp:change_password'%}">Change Password</a></li>
              <!-- <li><a href="#">{{user.username}}</a></li> -->
              <li class="btn"><a href="{% url 'payapp:logout'%}"><i class="fa-solid fa-unlock"></i> Logout</a></li>
            {% endif %}
            {% if not user.is_authenticated %}
              <li class="btn"><a href="{% url 'payapp:login'%}"><i class="fa-solid fa-unlock"></i> Login</a></li>
              <li class="btn"><a href="{% url 'payapp:accoutant_create'%}"><i class="fa-solid fa-user"></i>Sign Up</a></li>
            {% endif %}
              </ul>
            <div class="icon menu-btn">
              <i class="fas fa-bars"></i>
            </div>
          </div>
        </nav>
  <!-- </div> -->
  <div class="main">
    <main class="mainbar">
        <div class="dashboard-section">
            <p class="dashboard-title">Accountant Details</p>
            <br>
            <div class="parent-flex">
                <div class="number number-1">
                   <span class="title">Accountant User Id</span>: {{request.user.id}}
                </div>
                <div class="number number-2">
                    <span class="title">Account Name</span> : {{request.user.username}} 
                </div>
                <div class="number number-3">
                    <span class="title"> Accountant Email </span>: {{request.user.email}}
                </div>
                <div class="number number-4">
                    <span class="title">Admin status</span> : {{request.user.accountant.is_admin}}
                </div>
                <br>
                <a class="button-url p-3" href="{% url 'payapp:accountant_update'%}">Update</a>
                <br>
                <!-- <div class="number number-5">
                    <span class="title"> API</span>: Stripe
                </div>
                <div class="number number-6">
                    <span class="title"> College</span>: Orchid International College
                </div>
                <div class="number number-7">
                    <span class="title">Framework</span> : Django
                </div>
                <div class="number number-8">
                    <span class="title">Project</span> : 123
                </div> -->
            </div>
        </div>
    </main>
  </div>
  </div>
</body>
</html>


<script type="text/javascript">
    const body = document.querySelector("body");
    const navbar = document.querySelector(".navbar");
    const menuBtn = document.querySelector(".menu-btn");
    const cancelBtn = document.querySelector(".cancel-btn");
    menuBtn.onclick = ()=>{
      navbar.classList.add("show");
      menuBtn.classList.add("hide");
      body.classList.add("disabled");
    }
    cancelBtn.onclick = ()=>{
      body.classList.remove("disabled");
      navbar.classList.remove("show");
      menuBtn.classList.remove("hide");
    }
    window.onscroll = ()=>{
      this.scrollY > 20 ? navbar.classList.add("sticky") : navbar.classList.remove("sticky");
    }
  </script>

payapp/templates/payapp/balance_view.html
{% load static %}
<!DOCTYPE html> 
<html lang="en">
  <title>Hamro Khata | Welcome</title>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS Stylesheet -->
    <link rel="stylesheet" href="{% static 'css/detail_view.css'%}">
    <!-- Fontawesome -->
    <script src="https://kit.fontawesome.com/ae4127b743.js" crossorigin="anonymous"></script>
</head>
<body>
    <div class="header">
        <nav class="navbar">
          <div class="content">
            <div class="logo">
              <a href="{% url 'payapp:index'%}"><i class="fa-solid fa-pen-to-square"></i> Hamro Khata</a>
            </div>
            <ul class="menu-list">
              <div class="icon cancel-btn">
                <i class="fas fa-times"></i>
              </div>
              {% if user.is_authenticated %}
              {%if not user.is_staff%}
                <!-- Employee Status -->
                <li><a href="{% url 'payapp:balance' user.employee.id%}">View Balance</a></li>
                <li><a href="{% url 'payapp:employee_details'%}">Your Details</a></li>        
              {% else %}
                {% if not user.is_superuser %}
                  {% if user.accountant.is_admin %}
                  <!-- Admin Accountant Status -->
                  <li><a href="{% url 'payapp:payment_list' %}">Transactions</a></li>
                  <li><a href="https://dashboard.stripe.com/acct_1Lz101IdZsEKyeut/test/balance">Tax Fund</a></li>
                  {% endif %}
                  <!--Accountant Status -->
                  <li><a href="{% url 'payapp:payment_create'%}">Pay Salary</a></li>
                  <li><a href="{% url 'payapp:accountant_details'%}">Your Details</a></li>
                  <li><a href="{% url 'payapp:employee_list' %}">Employee</a></li>
                {% elif user.is_superuser %}
                <!-- Super User Status -->
                <li><a href="{% url 'admin:index' %}">Admin Panel</a></li>
                <li><a href="{% url 'payapp:users_list'%}">System Users</a></li>
                {% endif %}
              {% endif %}
              <li><a href="{% url 'payapp:change_password'%}">Change Password</a></li>
              <!-- <li><a href="#">{{user.username}}</a></li> -->
              <li class="btn"><a href="{% url 'payapp:logout'%}"><i class="fa-solid fa-unlock"></i> Logout</a></li>
            {% endif %}
            {% if not user.is_authenticated %}
              <li class="btn"><a href="{% url 'payapp:login'%}"><i class="fa-solid fa-unlock"></i> Login</a></li>
              <li class="btn"><a href="{% url 'payapp:accoutant_create'%}"><i class="fa-solid fa-user"></i>Sign Up</a></li>
            {% endif %}

              </ul>
            <div class="icon menu-btn">
              <i class="fas fa-bars"></i>
            </div>
          </div>
        </nav>
  <!-- </div> -->
  <div class="main">
    <main class="mainbar">
        <div class="dashboard-section">
            <p class="dashboard-title">{{user}}'s balance</p>
            <br>
            <div class="parent-flex">
                <div class="number number-1">
                   <span class="title">Employee Id</span>: {{request.user.id}}
                </div>
                <div class="number number-2">
                    <span class="title">Employee Name</span> : {{request.user.username}} 
                </div>
                <div class="number number-3">
                    <span class="title"> Total Balance </span>: {{total_salary}}
                </div>
                <div class="number number-4">
                    <span class="title">Provident fund Balance</span> : {{total_provident_fund}}
                </div>
                <div class="number number-5">
                  <span class="title"> Deducted Tax Amount</span>: {{total_tax}}
              </div>
                <br>
                <a class="button-url w-2" href="{% url 'payapp:transaction' user.employee.id%}">Transaction Details</a> <br>
                <a class="button-url w-15" href="https://dashboard.stripe.com/{{user.employee.strip_account_id}}/test/balance" target="_blank">Stripe Dashboard</a>            
                <br>
                <!-- <div class="number number-6">
                    <span class="title"> College</span>: Orchid International College
                </div>
                <div class="number number-7">
                    <span class="title">Framework</span> : Django
                </div>
                <div class="number number-8">
                    <span class="title">Project</span> : 123
                </div> -->
            </div>
        </div>
    </main>
  </div>
  </div>
</body>
</html>


<script type="text/javascript">
    const body = document.querySelector("body");
    const navbar = document.querySelector(".navbar");
    const menuBtn = document.querySelector(".menu-btn");
    const cancelBtn = document.querySelector(".cancel-btn");
    menuBtn.onclick = ()=>{
      navbar.classList.add("show");
      menuBtn.classList.add("hide");
      body.classList.add("disabled");
    }
    cancelBtn.onclick = ()=>{
      body.classList.remove("disabled");
      navbar.classList.remove("show");
      menuBtn.classList.remove("hide");
    }
    window.onscroll = ()=>{
      this.scrollY > 20 ? navbar.classList.add("sticky") : navbar.classList.remove("sticky");
    }
  </script>

payapp/templates/payapp/payment_list.html
{% load static %}
<!DOCTYPE html> 
<html lang="en">
  <title>Payment Lists | Hamro Khata</title>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS Stylesheet -->
    <link rel="stylesheet" href="{% static 'css/dashboard.css'%}">
    <!-- Fontawesome -->
    <script src="https://kit.fontawesome.com/ae4127b743.js" crossorigin="anonymous"></script>
</head>
<div class="header">
    <nav class="navbar">
      <div class="content">
        <div class="logo">
          <a href="{% url 'payapp:index'%}"><i class="fa-solid fa-pen-to-square"></i> Hamro Khata</a>
        </div>
        <ul class="menu-list">
          <div class="icon cancel-btn">
            <i class="fas fa-times"></i>
          </div>
          {% if user.is_authenticated %}
          {%if not user.is_staff%}
            <!-- Employee Status -->
            <li><a href="{% url 'payapp:balance' user.employee.id%}">View Balance</a></li>
            <li><a href="{% url 'payapp:employee_details'%}">Your Details</a></li>        
          {% else %}
            {% if not user.is_superuser %}
              {% if user.accountant.is_admin %}
              <!-- Admin Accountant Status -->
              <li><a href="{% url 'payapp:payment_list' %}">Transactions</a></li>
              <li><a href="https://dashboard.stripe.com/acct_1Lz101IdZsEKyeut/test/balance">Tax Fund</a></li>
              {% endif %}
              <!--Accountant Status -->
              <li><a href="{% url 'payapp:payment_create'%}">Pay Salary</a></li>
              <li><a href="{% url 'payapp:accountant_details'%}">Your Details</a></li>
              <li><a href="{% url 'payapp:employee_list' %}">Employee</a></li>
            {% elif user.is_superuser %}
            <!-- Super User Status -->
            <li><a href="{% url 'admin:index' %}">Admin Panel</a></li>
            <li><a href="{% url 'payapp:users_list'%}">System Users</a></li>
            {% endif %}
          {% endif %}
          <li><a href="{% url 'payapp:change_password'%}">Change Password</a></li>
          <!-- <li><a href="#">{{user.username}}</a></li> -->
          <li class="btn"><a href="{% url 'payapp:logout'%}"><i class="fa-solid fa-unlock"></i> Logout</a></li>
        {% endif %}
        {% if not user.is_authenticated %}
          <li class="btn"><a href="{% url 'payapp:login'%}"><i class="fa-solid fa-unlock"></i> Login</a></li>
          <li class="btn"><a href="{% url 'payapp:accoutant_create'%}"><i class="fa-solid fa-user"></i>Sign Up</a></li>
        {% endif %}
          </ul>
        <div class="icon menu-btn">
          <i class="fas fa-bars"></i>
        </div>
      </div>
    </nav>
  <!-- </div> -->
  <div class="main">
    <main class="mainbar">
        <div class="dashboard-section">
            <p class="dashboard-title">Payment List</p>
            <a class= "button-url m-l-2" href="{% url 'payapp:payment_create'%}">Create Payment</a>
            <div class="table">
                <div class="tr th">
                    <div class="td thead td-1">Payment Id</div>
                    <div class="td thead td-2">Employee Name</div>
                    <div class="td thead td-3">pf Deduction</div>
                    <div class="td thead td-4">tax deduction</div>
                    <div class="td thead td-5">Paid Salary</div>
                    <div class="td thead td-6">Payment Date</div>
                </div>
                {% for payment in payments %}
                <div class="tr">
                    <div class="td td-1">{{payment.id}}</div>
                    <div class="td td-2">{{payment.employee}}</div>
                    <div class="td td-3">
                        {{payment.pf_amount}}
                    </div>
                    <div class="td td-4">{{payment.tax_amount}}</div>
                    <div class="td td-5">{{payment.paid_salary}}</div>
                    <div class="td td-6">{{payment.payment_date}}</div>
                </div>
                {% endfor %}
            </div>
        </div>
    </main>
  </div>
  </div>
</body>
</html>


<script type="text/javascript">
    const body = document.querySelector("body");
    const navbar = document.querySelector(".navbar");
    const menuBtn = document.querySelector(".menu-btn");
    const cancelBtn = document.querySelector(".cancel-btn");
    menuBtn.onclick = ()=>{
      navbar.classList.add("show");
      menuBtn.classList.add("hide");
      body.classList.add("disabled");
    }
    cancelBtn.onclick = ()=>{
      body.classList.remove("disabled");
      navbar.classList.remove("show");
      menuBtn.classList.remove("hide");
    }
    window.onscroll = ()=>{
      this.scrollY > 20 ? navbar.classList.add("sticky") : navbar.classList.remove("sticky");
    }
  </script>